parameters:
    directora: Lic. Keila Mendoza</span><br>Directora General de Recursos Humanos<br><br>ZR/yy
    #directora: Lic. Eliana Bencomo</span><br>Directora General de Recursos Humanos (E)<br><br>ZR/yy
    montoticket: 135.000,00 Bsf.
    
