UsuarioBundle_nivelorganizacional:
    resource: "@UsuarioBundle/Resources/config/routing/nivelorganizacional.yml"
    prefix:   /nivelorganizacional
    
UsuarioBundle_organigrama:
    resource: "@UsuarioBundle/Resources/config/routing/organigrama.yml"
    prefix:   /organigrama
    
UsuarioBundle_perfil:
    resource: "@UsuarioBundle/Resources/config/routing/perfil.yml"
    prefix:   /perfil
    
UsuarioBundle_usuario:
    resource: "@UsuarioBundle/Resources/config/routing/usuario.yml"
    prefix:   /
    
UsuarioBundle_rol:
    resource: "@UsuarioBundle/Resources/config/routing/rol.yml"
    prefix:   /
    

#OTROS
telesur_personal:
    pattern:  /telesur/personal
    defaults: { _controller: UsuarioBundle:Personal:index }

usuario_homepage:
    pattern:  /inicio
    defaults: { _controller: UsuarioBundle:Default:index }

usuario_login:
    pattern: /login
    defaults: { _controller: UsuarioBundle:Default:login }
    
usuario_login_check:
    pattern: /login_check
    defaults: { _controller: UsuarioBundle:Default:loginCheck }
    
usuario_logout:
    pattern: /logout

contacto:
    pattern: /contacto
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'UsuarioBundle:Default:contacto.html.twig'

cambioclave:
    pattern:  /cambioclave
    defaults: { _controller: "UsuarioBundle:User:cambioclave" }

actualizacambioclave:
    pattern:  /actualizacambioclave
    defaults: { _controller: "UsuarioBundle:User:actualizacambioclave" }

notificar:
    pattern:  /notificar
    defaults: { _controller: "UsuarioBundle:User:notificar" }