videoteca_homepage:
    pattern:  /
    defaults: { _controller: VideotecaBundle:Default:index }

videoteca_consulta:
    pattern:  /consulta/{id}
    defaults: { _controller: VideotecaBundle:Default:consulta }