parameters:
    sproyecciones: "margarcia@telesurtv.net,jalvarado@telesurtv.net,electromecanica@telesurtv.net"
    sala4: "krivas@telesurtv.net"
    sala1: " mmarquez@telesurtv.net,laguerrero@telesurtv.net"
    estudio: "dbastidas@telesurtv.net,larvelo@telesurtv.net,averhelst@telesurtv.net,mpenaloza@telesurtv.net,alugo@telesurtv.net,jnadales@telesurtv.net,amarquez@telesurtv.net" 
    cabina: "mafernandez@telesurtv.net,alegonzalez@telesurtv.net"
    protocolo: "sduarte@telesurtv.net,mleon@telesurtv.net,marojas@telesurtv.net,dpatino@telesurtv.net,irodrigues@telesurtv.net,jmartinez@telesurtv.net,arivas@telesurtv.net,ysandoval@telesurtv.net,seguridad@telesurtv.net,protocolosuplente@telesurtv.net"
