parameters:
#    proyecto.example.class: Frontend\ProyectoBundle\Example

services:
#    proyecto.example:
#        class: %proyecto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    proyectoServicio:
        class: Frontend\ProyectoBundle\Servicio\proyectoServicio
            
    tareaServicio:
        class: Frontend\ProyectoBundle\Servicio\tareaServicio

    proyectoModelo:
        class: Frontend\ProyectoBundle\Modelo\proyectoModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"
            
    tareaModelo:
        class: Frontend\ProyectoBundle\Modelo\tareaModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"