parameters:
#    ticket.example.class: Progis\TicketBundle\Example

services:
#    ticket.example:
#        class: %ticket.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    validaProcesoTicketModelo:
        class: Progis\TicketBundle\Modelo\validaProcesoTicketModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"