ProyectoBundle_proyecto:
    resource: "@ProyectoBundle/Resources/config/routing/proyecto.yml"
    prefix:   /

ProyectoBundle_objetivo:
    resource: "@ProyectoBundle/Resources/config/routing/objetivo.yml"
    prefix:   /objetivo

ProyectoBundle_comentarioactividad:
    resource: "@ProyectoBundle/Resources/config/routing/comentarioactividad.yml"
    prefix:   /comentarioactividad
    
ProyectoBundle_documentoctividad:
    resource: "@ProyectoBundle/Resources/config/routing/documentoactividad.yml"
    prefix:   /documentoactividad

Proyecto_comentarios:
    resource: "@ProyectoBundle/Resources/config/routing/comentario.yml"
    prefix: /comentario

Proyecto_documentos:
    resource: "@ProyectoBundle/Resources/config/routing/documento.yml"
    prefix: /documento

Proyecto_proceso:
    path:     /lista/proceso
    defaults: { _controller: "ProyectoBundle:Default:proceso" }

Proyecto_revisar:
    path:     /lista/revisar
    defaults: { _controller: "ProyectoBundle:Default:revisar" }
    
Proyecto_pendiente:
    path:     /lista/pentiente
    defaults: { _controller: "ProyectoBundle:Default:pendiente" }
    
Proyecto_buscar:
    path:     /buscarproyecto
    defaults: { _controller: "ProyectoBundle:Default:buscar" }
    requirements: { _method: post }

proyecto_procesarActividad:
    path:     /procesarActividad/{idobjetivo}
    defaults: { _controller: ProyectoBundle:ProcesarActividad:procesarActividad }
  
actividad_show:
    path:     /{id}/show
    defaults: { _controller: "ProyectoBundle:ProcesarActividad:show" }
    
actividad_new:
    path:     /new/{idobjetivo}/procesarActividad
    defaults: { _controller: "ProyectoBundle:ProcesarActividad:new" }

actividad_create:
    path:     /create/{idobjetivo}
    defaults: { _controller: "ProyectoBundle:ProcesarActividad:create" }
    requirements: { _method: post }

actividad_edit:
    path:     /edit/{id}/procesarActividad
    defaults: { _controller: "ProyectoBundle:ProcesarActividad:edit" }

actividad_update:
    path:     /{id}/update/procesarActividad
    defaults: { _controller: "ProyectoBundle:ProcesarActividad:update" }
    requirements: { _method: post|put }

actividad_delete:
    path:     /actividad/{id}/delete
    defaults: { _controller: "ProyectoBundle:ProcesarActividad:delete" }
    requirements: { _method: post|delete }
    
progis_proyecto_justificaractividad:
    path:     /justificarActividad/{idactividad}
    defaults: { _controller: ProyectoBundle:ProcesarActividad:JustificarActividad }
    
    
ProyectoBundle_miembroproyecto:
    resource: "@ProyectoBundle/Resources/config/routing/miembroproyecto.yml"
    prefix:   /miembroproyecto
