parameters:
#    formulario.example.class: Frontend\FormularioBundle\Example

services:
#    formulario.example:
#        class: %formulario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
