parameters:
#    encuesta.example.class: Frontend\EncuestaBundle\Example

services:
#    encuesta.example:
#        class: %encuesta.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     trivias:
         class: Frontend\EncuestaBundle\Servicios\trivias
         arguments:
            em: "@doctrine.orm.entity_manager"
