<?php

namespace Frontend\ControlEquipoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Frontend\ControlEquipoBundle\Entity\Marcas;
use Frontend\ControlEquipoBundle\Entity\Modelos;
/**
 * ModelosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelosRepository extends EntityRepository
{
    public function findByMarcaId($marca_id)
    {

         $query = $this->getEntityManager()->createQuery("
            SELECT modelo.id,modelo.descripcionModelo
            FROM ControlEquipoBundle:Modelos modelo
            JOIN modelo.marca marca
            WHERE marca.id = :marca_id
        ")->setParameter('marca_id', $marca_id);
        return $query->getArrayResult();
    }
}