parameters:
#    datatable.example.class: Administracion\DatatableBundle\Example

services:
#    datatable.example:
#        class: %datatable.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
