parameters:
#    nomina.example.class: Frontend\NominaBundle\Example

services:
#    nomina.example:
#        class: %nomina.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    Historico_Modelo:
        class: Frontend\NominaBundle\Modelo\Historico
        arguments: 
            em: "@doctrine.orm.entity_manager"