parameters:
#    principal.example.class: Progis\PrincipalBundle\Example

services:
#    principal.example:
#        class: %principal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    ubicacionModelo:
        class: Progis\PrincipalBundle\Modelo\ubicacionModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"
            
    ordenModelo:
        class: Progis\PrincipalBundle\Modelo\ordenModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"
            
    procesaModelo:
        class: Progis\PrincipalBundle\Modelo\procesaModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"
            
    funcionModelo:
        class: Progis\PrincipalBundle\Modelo\funcionModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"
            
    ticketModelo:
        class: Progis\TicketBundle\Modelo\ticketModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"
            
    bitacoraModelo:
        class: Progis\PrincipalBundle\Modelo\bitacoraModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"
            
    seguridadModelo:
        class: Progis\PrincipalBundle\Modelo\seguridadModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"

    metaModelo:
        class: Progis\PrincipalBundle\Modelo\metaModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"
            
    productividadModelo:
        class: Progis\PrincipalBundle\Modelo\productividadModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"
            
    TrabajoRealizadoModelo:
        class: Progis\PrincipalBundle\Modelo\TrabajoRealizadoModelo
        arguments: 
            em: "@doctrine.orm.entity_manager"
            container: "@service_container"
