prioridadmeta:
    path:     /
    defaults: { _controller: "PrincipalBundle:Prioridadmeta:index" }

prioridadmeta_show:
    path:     /{id}/show
    defaults: { _controller: "PrincipalBundle:Prioridadmeta:show" }


prioridadmeta_edit:
    path:     /{id}/edit
    defaults: { _controller: "PrincipalBundle:Prioridadmeta:edit" }

prioridadmeta_update:
    path:     /{id}/update
    defaults: { _controller: "PrincipalBundle:Prioridadmeta:update" }
    requirements: { _method: post|put }

prioridadmeta_delete:
    path:     /{id}/delete
    defaults: { _controller: "PrincipalBundle:Prioridadmeta:delete" }
    requirements: { _method: post|delete }
