invitados:
    path:     /
    defaults: { _controller: "ProtocoloBundle:Invitados:index" }

invitados_show:
    path:     /{id}/show
    defaults: { _controller: "ProtocoloBundle:Invitados:show" }

invitados_new:
    path:     /new
    defaults: { _controller: "ProtocoloBundle:Invitados:new" }

invitados_create:
    path:     /create
    defaults: { _controller: "ProtocoloBundle:Invitados:create" }
    requirements: { _method: post }

invitados_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProtocoloBundle:Invitados:edit" }

invitados_update:
    path:     /{id}/update
    defaults: { _controller: "ProtocoloBundle:Invitados:update" }
    requirements: { _method: post|put }

invitados_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProtocoloBundle:Invitados:delete" }
    requirements: { _method: post|delete }
