parameters:
    transporte: "transporte@telesurtv.net,tutransporte@telesurtv.net"
    soporte: "soporte@telesurtv.net"
    protocolo: "sduarte@telesurtv.net,mleon@telesurtv.net,dpatino@telesurtv.net,irodrigues@telesurtv.net,arivas@telesurtv.net,ysandoval@telesurtv.net,seguridad@telesurtv.net, protocolosuplente@telesurtv.net,ohutson@telesurtv.net,fcouto@telesurtv.net"
