parameters:
#    protocolo.example.class: Frontend\ProtocoloBundle\Example

services:
#    protocolo.example:
#        class: %protocolo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
