misproductos:
    path:     /
    defaults: { _controller: "TruequesBundle:MisProductos:index" }

misproductos_show:
    path:     /{id}/show
    defaults: { _controller: "TruequesBundle:MisProductos:show" }

misproductos_new:
    path:     /new
    defaults: { _controller: "TruequesBundle:MisProductos:new" }

misproductos_create:
    path:     /create
    defaults: { _controller: "TruequesBundle:MisProductos:create" }
    requirements: { _method: post }

misproductos_edit:
    path:     /{id}/edit
    defaults: { _controller: "TruequesBundle:MisProductos:edit" }

misproductos_update:
    path:     /{id}/update
    defaults: { _controller: "TruequesBundle:MisProductos:update" }
    requirements: { _method: post|put }

misproductos_delete:
    path:     /{id}/delete
    defaults: { _controller: "TruequesBundle:MisProductos:delete" }
    requirements: { _method: post|delete }